---

- include: repository.yml
  tags: pgbouncer

# needed to get some stats
- apt: pkg={{ pgbouncer.postgres_client_package_name }} state=present

- name: Install pgbouncer
  apt: pkg=pgbouncer state=installed
  notify:
    - restart pgbouncer
  tags: pgbouncer

- name: Install pgbouncer config
  action: template src=pgbouncer/pgbouncer.ini.j2 dest=/etc/pgbouncer/pgbouncer.ini
          mode=0644 owner={{ pgbouncer.user }} group={{ pgbouncer.group }}
  notify:
    - reload pgbouncer
  tags: pgbouncer

- template: src=pgbouncer/users.txt.j2 dest={{ pgbouncer.config.auth_file }} owner={{ pgbouncer.user }}
  notify:
    - reload pgbouncer
  tags: pgbouncer

- lineinfile: dest=/etc/default/pgbouncer regexp=^START=1$ line=START=1 state=present
  notify:
    - reload pgbouncer
  tags: pgbouncer

- lineinfile: dest=/etc/default/pgbouncer regexp=^START=0$ line=START=0 state=absent
  notify:
    - reload pgbouncer
  tags: pgbouncer

- template: src=pgbouncer/logrotate.j2 dest=/etc/logrotate.d/postgresql-common

- include: monitoring.yml
  when: pgbouncer_monit is defined and pgbouncer_monit|bool == true
  tags: pgbouncer

- include: newrelic.yml
  when: newrelic_license_key is defined and pgbouncer_newrelic_install|bool == true
  tags: pgbouncer

- include: create_readonly_user.yml
  when: pgbouncer_create_readonly_user is defined and pgbouncer_create_readonly_user|bool == true

- name: change permissions of log folder
  file:
    path: /var/log/postgresql
    owner: postgres
    group: postgres
    mode: 0744
