---

# needed to get some stats
- apt: pkg={{ pgbouncer.postgres_client_package_name }} state=present

- name: stats
  command: psql -p {{ pgbouncer.config.listen_port }} pgbouncer -U {{ pgbouncer_stats_users | first }} -c "show {{ item }};"
  register: stats_output
  with_items:
    - stats
    - pools
    - databases
    - servers
    - clients
    - mem
  when: pgbouncer_command == 'stats'

- debug: var="{{ stats_output.results }}"
  when: pgbouncer_command == 'stats'

- name: pause
  command: psql -p {{ pgbouncer.config.listen_port }} pgbouncer -U {{ pgbouncer_admin_users | first }} -c "pause {{ pgbouncer_command_db }};"
  when: pgbouncer_command == 'pause'

- name: resume
  command: psql -p {{ pgbouncer.config.listen_port }} pgbouncer -U {{ pgbouncer_admin_users | first }} -c "resume {{ pgbouncer_command_db }};"
  when: pgbouncer_command == 'resume'

- name: reload
  service: name=pgbouncer state=reloaded
  when: pgbouncer_command == 'reload'